import importlib.util
import json
from pathlib import Path
import tempfile
import unittest

spec = importlib.util.spec_from_file_location('q2b', Path(__file__).parents[1] / 'sc_q2b.py')
q = importlib.util.module_from_spec(spec)
spec.loader.exec_module(q)

class DiagnosticContracts(unittest.TestCase):
    def test_reference_count_never_becomes_object_path(self):
        self.assertEqual(q.engine_object_paths('- Reference count: 1'), [])
        rec = self.record()
        for instance in rec['facts']['instances']: instance['path_extra'] = '- Reference count: 1'
        derived = q.derive([rec])['signatures'][0]
        self.assertEqual(derived['object_paths'], [])
        self.assertEqual(derived['engine_object_path_status'], 'NOT_OBSERVED')

    def test_explicit_engine_path_fields_parse(self):
        self.assertEqual(q.engine_object_paths(' - Resource path: res://audio/loop.wav - Reference count: 1'), [{'kind':'Resource path','value':'res://audio/loop.wav'}])
        self.assertEqual(q.engine_object_paths('- Node path: /root/Main/Emitter'), [{'kind':'Node path','value':'/root/Main/Emitter'}])
        rec = self.record(); rec['facts']['instances'][0]['path_extra'] = '- Resource path: res://audio/loop.wav - Reference count: 1'
        self.assertEqual(q.derive([rec])['signatures'][0]['object_paths'], ['res://audio/loop.wav'])

    def test_absent_engine_path_is_not_inferred(self):
        for tail in ('', '- Reference count: 8', '- ObjectID: 101', '- Node name: WindPlayer', '- Type: AudioStreamWAV'):
            self.assertEqual(q.engine_object_paths(tail), [])
        rec=self.record()
        self.assertEqual(q.derive([rec])['signatures'][0]['object_paths'], [])

    def tree_fixture(self, streamer_name='@Node3D@51'):
        root='WorldManager/'+streamer_name
        entries=['.|Node3D','WorldManager|Node3D','WorldManager/SessionDiagnostics|Node',root+'|Node3D',root+'/Chunk_0|Node3D',root+'/Chunk_0/@MeshInstance3D@5|MeshInstance3D','@Node3D@elsewhere|Node3D','@Node3D@elsewhere/@Node3D@retained|Node3D','HUD|Control','HUD/@Node3D@unrelated|Node3D']
        owned=[{'cycle':1,'group':'T-WORLD','role':role,'class':cl} for role,cl in [('WorldManager','Node3D'),('ChunkStreamer','Node3D'),('RoadChunk','Node3D')]]
        return entries,owned

    def test_autogenerated_streamer_name_does_not_defeat_exclusion(self):
        entries,owned=self.tree_fixture()
        corrected=q.normalise_tree(entries,owned,1,1)
        self.assertEqual(corrected['streamer_raw_path'],'WorldManager/@Node3D@51')
        self.assertEqual(len(corrected['excluded_descendants']),2)
        self.assertIn('WorldManager/ChunkStreamer|Node3D',corrected['normalised_entries'])
        renamed,roles=self.tree_fixture('some_other_runtime_name')
        self.assertEqual(corrected['digest'],q.normalise_tree(renamed,roles,1,1)['digest'])

    def test_unrelated_autogenerated_nodes_are_retained(self):
        entries,owned=self.tree_fixture()
        corrected=q.normalise_tree(entries,owned,1,1)['normalised_entries']
        self.assertIn('@Node3D@elsewhere|Node3D',corrected)
        self.assertIn('@Node3D@elsewhere/@Node3D@retained|Node3D',corrected)
        self.assertIn('HUD/@Node3D@unrelated|Node3D',corrected)

    def test_tree_normalisation_is_deterministic(self):
        entries,owned=self.tree_fixture()
        first=q.normalise_tree(entries,owned,1,1)
        second=q.normalise_tree(list(reversed(entries)),list(reversed(owned)),1,1)
        self.assertEqual(first,second)

    def test_ambiguous_or_missing_frozen_identity_stops(self):
        entries,owned=self.tree_fixture()
        for changed,roles,count in [(entries+['WorldManager/@Node3D@other|Node3D'],owned,1),(entries,[],1),(entries,owned,2),(entries+['WorldManager|Node3D'],owned,1)]:
            with self.assertRaisesRegex(ValueError,'FROZEN_TREE_EVIDENCE_INSUFFICIENT'):
                q.normalise_tree(changed,roles,1,count)

    def test_missing_and_wrong_cycle_composition_witness_stops(self):
        entries,owned=self.tree_fixture()
        wrong=entries.copy();wrong[4]='WorldManager/@Node3D@51/Unrelated|Node3D'
        for changed,cycle in [(wrong,1),(entries,2)]:
            with self.assertRaisesRegex(ValueError,'FROZEN_TREE_EVIDENCE_INSUFFICIENT'):
                q.normalise_tree(changed,owned,cycle,1)

    def test_fixed_matrix_order_and_no_pooling(self):
        matrix = json.loads((Path(__file__).parents[1]/'q2b_matrix.json').read_text())['attempts']
        self.assertEqual([r['ordinal'] for r in matrix], list(range(1, 151)))
        self.assertEqual(sum(r['verbose'] for r in matrix), 36)
        self.assertFalse(matrix[20]['verbose'])
        for t in range(30):
            expected = [('NORMAL','AUDIO_REMOVED','WAIT'), ('AUDIO_REMOVED','WAIT','NORMAL'), ('WAIT','NORMAL','AUDIO_REMOVED')][t%3]
            self.assertEqual(tuple(r['arm'] for r in matrix[37+3*t:40+3*t]), expected)
        self.assertEqual(sum(r['block']=='D2-I' for r in matrix), 90)

    def test_fisher_direction_and_exact_value(self):
        self.assertAlmostEqual(q.fisher(7,30,0,30), 2035800/386206920, places=12)
        self.assertGreater(q.fisher(0,30,7,30), .99)
        self.assertEqual(q.fisher(0,30,0,30), 1)

    def test_exact_interval_boundaries(self):
        self.assertAlmostEqual(q.interval(0,30)[1], 1-.025**(1/30))
        self.assertAlmostEqual(q.interval(30,30)[0], .025**(1/30))
        self.assertEqual(q.interval(0,30)[0], 0)
        self.assertIsNone(q.interval(0,0))

    def record(self, ids=(101,102), ordinal=1):
        return {'ordinal': ordinal, 'block': 'D1-P', 'arm': 'NORMAL', 'infra': False,
            'facts': {'warning_counts': [2], 'instances': [{'id': i, 'class': c, 'path_extra': ''} for i,c in zip(ids,('AudioStreamWAV','AudioStreamPlaybackWAV'))],
                      'owned': [{'id':101,'class':'AudioStreamWAV','group':'T-AUDIO','role':'WindPlayer.stream','playing':'true'},
                                {'id':102,'class':'AudioStreamPlaybackWAV','group':'T-AUDIO','role':'WindPlayer.get_stream_playback()','playing':'true'}]}}

    def test_same_process_attribution_required(self):
        self.assertEqual(q.derive([self.record()])['k'], 1)
        self.assertEqual(q.derive([self.record(ids=(201,202))])['k'], 0)
        first, second = self.record(ids=(201,202)), self.record(ordinal=2)
        first['facts']['owned'], second['facts']['owned'] = second['facts']['owned'], []
        self.assertEqual(q.derive([first,second])['k'], 0)

    def test_no_signature_from_count_or_partial_mapping(self):
        rec = self.record(); rec['facts']['instances'] = []
        self.assertEqual(q.derive([rec])['k'], 0)
        rec = self.record(); rec['facts']['owned'].pop()
        self.assertEqual(q.derive([rec])['k'], 0)

    def test_multiplicity_frozen_and_incidence_only(self):
        rec = self.record(); other = self.record(ordinal=2)
        other['facts']['owned'][0]['role'] = 'GravelPlayer.stream'
        frozen = q.derive([rec,other]); self.assertEqual(frozen['adjusted_alpha'], .005)
        output = q.aggregate([rec,other], frozen)
        self.assertEqual(output['signatures'][0]['arms']['NORMAL']['n'], 0)

    def test_channel_raw_parsing_and_unsigned_ids(self):
        with tempfile.TemporaryDirectory() as d:
            directory = Path(d)
            raw = b'Leaked instance: AudioStreamWAV:9223372036854775809\r\n'
            (directory/'stdout.log').write_bytes(raw)
            (directory/'stderr.log').write_text('WARNING: 1 ObjectDB instances were leaked at exit\nSCRIPT ERROR: fixture\n')
            result = q.facts(directory)
            self.assertEqual(result['instances'][0]['id'], 9223372036854775809)
            self.assertEqual(result['channel_counts']['stderr']['warnings'], 1)
            self.assertEqual(result['channel_counts']['engine']['warnings'], 0)
            self.assertEqual((directory/'stdout.log').read_bytes(), raw)
            self.assertTrue(result['script_errors'])

    def test_retained_evidence_detects_tampering(self):
        with tempfile.TemporaryDirectory() as d:
            root = Path(d); (root/'raw.log').write_bytes(b'original')
            q.ledger(root, 'fixture', {'a':1}); q.retain(root)
            self.assertEqual(q.checksums(root), [])
            (root/'raw.log').write_bytes(b'changed')
            self.assertEqual(q.checksums(root), ['raw.log'])
